---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: appsdb
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-ops-manager-db-volume-0
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: appsdb
  local:
    path: /data/db/om0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mongod3
          - mongod4
          - mongod5
          - mongod6
          - mongod7
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-ops-manager-db-volume-1
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: appsdb
  local:
    path: /data/db/om1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mongod3
          - mongod4
          - mongod5
          - mongod6
          - mongod7
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-ops-manager-db-volume-2
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: appsdb
  local:
    path: /data/db/om2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mongod3
          - mongod4
          - mongod5
          - mongod6
          - mongod7
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-ops-manager-db-volume-3
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: appsdb
  local:
    path: /data/db/om3
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mongod3
          - mongod4
          - mongod5
          - mongod6
          - mongod7
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-ops-manager-db-volume-4
spec:
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: appsdb
  local:
    path: /data/db/om4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mongod3
          - mongod4
          - mongod5
          - mongod6
          - mongod7
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: ops-manager-backup-0
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: head-ops-manager-backup-daemon-volume-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 5Gi
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ops-manager-backup-0
  local:
    path: /data/db/bd0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mongod3
          - mongod4
          - mongod5
          - mongod6
          - mongod7
