---
apiVersion: mongodb.com/v1
kind: MongoDBOpsManager
metadata:
  name: {{ .Values.deploymentName }}
spec:
  # Ops Manager HTTP(S) section
  replicas: {{ .Values.opsManager.replicas }}
  version: {{ .Values.opsManager.omVersion }}
  adminCredentials: {{ .Values.opsManager.adminUserSecret }}
  statefulSet:
    spec:
      volumeClaimTemplates:
        - metadata:
            name: mongodb-binaries
          spec:
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: 5Gi
            storageClassName: ops-manager-binaries
      template:
        spec:
          containers:
            - name: mongodb-ops-manager
            {{- if .Values.opsManager.localBinariesMountEnabled }}
              volumeMounts:
                - mountPath: /mongodb-ops-manager/mongodb-releases
                  name: mongodb-binaries
            {{- end }}
              resources:
                limits:
                  cpu: {{ .Values.opsManager.podLimitCPU | quote }}
                  memory: {{ .Values.opsManager.podLimitMemory }}
                requests:
                  cpu: {{ .Values.opsManager.podRequestsCPU | quote }}
                  memory: {{ .Values.opsManager.podRequestsMemory }}
          initContainers:
          - name: mongodb-enterprise-init-ops-manager
            resources:
              limits:
                cpu: {{ .Values.opsManager.initPodLimitCPU | quote }}
                memory: {{ .Values.opsManager.initPodLimitMemory }}
              requests:
                cpu: {{ .Values.opsManager.initPodRequestsCPU | quote }}
                memory: {{ .Values.opsManager.initPodRequestsMemory }}
  configuration:
    {{- if .Values.opsManager.extServiceEnabled }}
    mms.centralUrl: {{ .Values.opsManager.extCentralUrl }}
    {{- end }}
    mms.ignoreInitialUiSetup: "true"
    automation.versions.source: {{ .Values.opsManager.binsarySource | default "remote" | quote }}
    mms.adminEmailAddr: {{ .Values.opsManager.adminEmailAddress }}
    mms.fromEmailAddr: {{ .Values.opsManager.fromEmailAddress }}
    mms.replyToEmailAddr: {{ .Values.opsManager.replyEmailAddress }}
    mms.mail.hostname: {{ .Values.opsManager.emailServerHostname }}
    mms.mail.port: {{ .Values.opsManager.emailPort | quote }}
    mms.mail.ssl: {{ .Values.opsManager.emailSecure | quote}}
    mms.mail.transport: {{ .Values.opsManager.emailProtocol }}
    mms.minimumTLSVersion: TLSv1.2

  security:
    tls:
      secretRef:
        name: {{ .Values.opsManager.tlsSecretName }}
{{ if .Values.opsManager.extServiceEnabled }}
  externalConnectivity:
    type: {{ .Values.opsManager.extServiceType }}
    {{- if eq .Values.opsManager.extServiceType "NodePort" }}
    port: {{ .Values.opsManager.extServicePort }}
    {{- end }}
{{- end }}

  # AppsDB section
  applicationDatabase:
    members: {{ .Values.appDB.replicas }}
    version: {{ .Values.appDB.mdbVersion }}
    passwordSecretKeyRef:
      name: {{ .Values.appDB.adminSecretName }} 
    security:
      tls:
        ca: {{ .Values.appDB.CAConfigmapName  }}
        secretRef:
          name: {{ .Values.appDB.tlsSecretName }}
    podSpec:
      podTemplate:
        spec:
          initContainers:
            - name: mongodb-enterprise-init-appdb
              resources:
                limits:
                  cpu: {{ .Values.appDB.initPodLimitCPU | quote }}
                  memory: {{ .Values.appDB.initPodLimitMemory }}
                requests:
                  cpu: {{ .Values.appDB.initPodRequestsCPU | quote }}
                  memory: {{ .Values.appDB.initPodRequestsMemory }}
          containers:
            - name: mongod
              resources:
                limits:
                  cpu: {{ .Values.appDB.podLimitCPU | quote }}
                  memory: {{ .Values.appDB.podLimitMemory }}
                requests:
                  cpu: {{ .Values.appDB.podRequestsCPU | quote }}
                  memory: {{ .Values.appDB.podRequestsMemory }}
      persistence:
        single:
          storage: {{ .Values.appDB.storageSize }}
          storageClass: {{ .Values.appDB.storageClass }}

# Backup section
  backup:
    enabled: {{ .Values.backups.enabled }}
{{- if .Values.backups.enabled }}
    members: {{ .Values.backups.members | default 1 }}
    statefulSet:
      spec:
        {{- if .Values.backups.head.binariesMountEnabled }}
        volumeClaimTemplates:
          - metadata:
              name: mongodb-binaries
            spec:
              accessModes: [ "ReadWriteOnce" ]
              resources:
                requests:
                  storage: {{ .Values.backups.head.binariesStorageSize }}
              storageClassName: {{ .Values.backups.head.binariesStorageClass }}
        {{- end }}
        template:
          spec:
            containers:
              - name: mongodb-backup-daemon
                {{- if .Values.backups.head.binariesMountEnabled }}
                volumeMounts:
                  - mountPath: /mongodb-ops-manager/mongodb-releases
                    name: mongodb-binaries
                {{- end }}
                resources:
                  limits:
                    cpu: {{ .Values.backups.head.podLimitCPU | quote }}
                    memory: {{ .Values.backups.head.podLimitMemory }}
                  requests:
                    cpu: {{ .Values.backups.head.podRequestsCPU | quote }}
                    memory: {{ .Values.backups.head.podRequestsMemory }}
            initContainers:
            - name: mongodb-enterprise-init-ops-manager
              resources:
                limits:
                  cpu: {{ .Values.backups.head.initPodLimitCPU | quote }}
                  memory: {{ .Values.backups.head.initPodLimitMemory }}
                requests:
                  cpu: {{ .Values.backups.head.initPodRequestsCPU | quote }}
                  memory: {{ .Values.backups.head.initPodRequestsMemory }}
    headDB:
      storage: {{ .Values.backups.head.storageSize }}
      storageClass: {{ .Values.backups.head.storageClass }}
    opLogStores:
    {{- range .Values.backups.oplogStores.stores }}
      - name: {{ .name }}
        mongodbResourceRef:
          name: {{ .mdbResource }}
        mongodbUserRef:
          name: {{ .userResource }}
    {{- end }}
    {{- if .Values.backups.blockstores }}
    {{- if gt (len .Values.backups.blockstores.stores) 0  }}
    blockStores:
    {{- range .Values.backups.blockstores.stores }}
      - name: {{ .name }}
        mongodbResourceRef:
          name: {{ .mdbResource }}
        mongodbUserRef:
          name: {{ .userResource }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- if .Values.backups.s3stores }}
    {{- if gt (len .Values.backups.s3stores.stores) 0  }}
    s3Stores:
    {{- range .Values.backups.s3stores.stores }}
      - name: {{ .name }}
        mongodbResourceRef:
          name: {{ .mdbResource }}
        mongodbUserRef:
          name: {{ .userResource }}
        s3SecretRef:
          name: {{ .s3secret}}
        pathStyleAccessEnabled: {{ .pathStyleEnabled | default true }}
        s3BucketEndpoint: {{ .bucketEndpoint | quote }}
        s3BucketName: {{ .bucketName }}
    {{- end }}
    {{- end }}
    {{- end }}
{{- end }}
