---

deploymentName: ops-manager

tls:
  enabled: true

opsManager:
  omVersion: 5.0.11
  replicas: 2
  adminUserSecret: om-admin-user
  binarySource: remote
  centralUrl: https://ops-manager-svc.mongodb.svc.cluster.local:8443
  emailServerHostname: mail0.mongodb.local
  adminEmailAddress: support@mongodb.local
  fromEmailAddress: support@mongodb.local
  replyEmailAddress: support@mongodb.local
  emailPort: 465
  emailSecure: true
  emailProtocol: smtp
  podLimitCPU: 4
  podRequestsCPU: 2
  podLimitMemory: 8Gi
  podRequestsMemory: 4Gi
  initPodLimitCPU: 2
  initPodRequestsCPU: 1
  initPodLimitMemory: 2Gi
  initPodRequestsMemory: 1Gi
  localBinariesMountEnabled: false
  localBinariesMountStorageClass: ops-manager-binaries
  localBinariesMountStorageSize: 5Gi
  extServiceEnabled: true
  extServiceType: NodePort
  extServicePort: 32111

appDB:
  replicas: 3
  mdbVersion: 5.0.5-ent
  mongoDBAdminPasswdSecretName: om-db-user
  CAConfigmapName: custom-ca
  podLimitCPU: 2
  podRequestsCPU: 2
  podLimitMemory: 2Gi
  podRequestsMemory: 2Gi
  storageClass: appsdb
  storageSize: 10Gi 

backups:
  enabled: false
  members: 1
  head:
    binariesMountEnabled: true
    binariesStorageClass: ops-manager-binaries
    binariesStorageSize: 1Gi
    storageClass: ops-manager-backup-0
    storageSize: 1Gi
    podLimitCPU: 2
    podRequestsCPU: 1
    podLimitMemory: 2Gi
    podRequestsMemory: 1Gi
    initPodLimitCPU: 2
    initPodRequestsCPU: 1
    initPodLimitMemory: 2Gi
    initPodRequestsMemory: 1Gi
  oplogStores:
    - name: oplogstore0
      mdbResource: oplogstore0
      userResource: oplogstore-oplog0-om-user
  blockStores:
    - name: blockstore0
      mdbResource: blockstore0
      userResource: blockstore-blockstore0-om-user
  s3stores: []
